import { BG_AZURE, BG_EMERALD, BG_MONO, BG_TEALMAG, BG_VIOLET } from "./options";

export const THEMES = [
  { id:"groen",  name:"Carbon · Groen",  ac:"#00c853", bg:"#08080a", pattern:"carbon" },
  { id:"goud",   name:"Carbon · Goud",   ac:"#d4af37", bg:"#0d0b08", pattern:"carbon" },
  { id:"blauw",  name:"Carbon · Blauw",  ac:"#1e88e5", bg:"#07080f", pattern:"carbon" },
  { id:"rood",   name:"Carbon · Rood",   ac:"#e53935", bg:"#0f0707", pattern:"arrows" },
  { id:"zilver", name:"Carbon · Zilver", ac:"#b0bec5", bg:"#0b0c0e", pattern:"grid"   },
  { id:"dual",            name:"Carbon · Dual",         ac:"#1565c0", ac2:"#ff6d00", bg:"#07080f", pattern:"dual" },
  { id:"dual-blauw-wit",  name:"Carbon · Blauw/Wit",    ac:"#1e88e5", ac2:"#f1f5f9", bg:"#07080f", pattern:"dual" },
  { id:"dual-groen-wit",  name:"Carbon · Groen/Wit",    ac:"#00c853", ac2:"#f1f5f9", bg:"#08080a", pattern:"dual" },
  { id:"dual-rood-wit",   name:"Carbon · Rood/Wit",     ac:"#e53935", ac2:"#f1f5f9", bg:"#0f0707", pattern:"dual" },
  { id:"dual-blauw-rood", name:"Carbon · Blauw/Rood",   ac:"#1565c0", ac2:"#e53935", bg:"#080610", pattern:"dual" },
  // ── Nieuwe achtergronden ──
  { id:"chevron",          name:"Chevron · Lime",     ac:"#a3e635", bg:"#080a06", pattern:"chevron" },
  { id:"chevron-cobalt",   name:"Chevron · Cobalt",   ac:"#2563eb", bg:"#060812", pattern:"chevron" },
  { id:"chevron-coral",    name:"Chevron · Coral",    ac:"#f97316", bg:"#0a0703", pattern:"chevron" },
  { id:"chevron-magenta",  name:"Chevron · Magenta",  ac:"#d946ef", bg:"#0a0610", pattern:"chevron" },
  { id:"stadium",          name:"Stadion · Oranje",   ac:"#fb923c", bg:"#0a0805", pattern:"stadium" },
  { id:"stadium-goud",     name:"Stadion · Goud",     ac:"#fbbf24", bg:"#0a0805", pattern:"stadium" },
  { id:"stadium-rood",     name:"Stadion · Rood",     ac:"#dc2626", bg:"#0a0505", pattern:"stadium" },
  { id:"stadium-smaragd",  name:"Stadion · Smaragd",  ac:"#059669", bg:"#050a07", pattern:"stadium" },
  { id:"grass",            name:"Veld · Smaragd",     ac:"#10b981", bg:"#050a08", pattern:"grass"   },
  { id:"grass-lime",       name:"Veld · Lime",        ac:"#84cc16", bg:"#070a05", pattern:"grass"   },
  { id:"grass-teal",       name:"Veld · Teal",        ac:"#14b8a6", bg:"#050a09", pattern:"grass"   },
  { id:"grass-mint",       name:"Veld · Mint",        ac:"#5eead4", bg:"#06090a", pattern:"grass"   },
  { id:"rays",             name:"Stralen · Magenta",  ac:"#ec4899", bg:"#0a0608", pattern:"rays"    },
  { id:"rays-goud",        name:"Stralen · Goud",     ac:"#f59e0b", bg:"#0a0805", pattern:"rays"    },
  { id:"rays-cyaan",       name:"Stralen · Cyaan",    ac:"#06b6d4", bg:"#050a0c", pattern:"rays"    },
  { id:"rays-lila",        name:"Stralen · Lila",     ac:"#c084fc", bg:"#08060c", pattern:"rays"    },
  { id:"dots",             name:"Halftone · Cyaan",   ac:"#06b6d4", bg:"#050a0c", pattern:"dots"    },
  { id:"dots-magenta",     name:"Halftone · Magenta", ac:"#ec4899", bg:"#0a0608", pattern:"dots"    },
  { id:"dots-geel",        name:"Halftone · Geel",    ac:"#facc15", bg:"#0a0a05", pattern:"dots"    },
  { id:"dots-lila",        name:"Halftone · Lila",    ac:"#a78bfa", bg:"#08060c", pattern:"dots"    },
  { id:"hex",              name:"Hexagon · Paars",    ac:"#a855f7", bg:"#08060c", pattern:"hex"     },
  { id:"hex-ijs",          name:"Hexagon · IJsblauw", ac:"#38bdf8", bg:"#050a0c", pattern:"hex"     },
  { id:"hex-goud",         name:"Hexagon · Goud",     ac:"#fbbf24", bg:"#0a0805", pattern:"hex"     },
  { id:"hex-roze",         name:"Hexagon · Roze",     ac:"#f43f5e", bg:"#0a0506", pattern:"hex"     },
  // ── Cinematic thema's (mist + glow + streaks) ──
  { id:"cinema-emerald", name:"Cinema · Smaragd/Oranje", ac:"#10b981", ac2:"#f59e0b", bg:"#06080a", pattern:"cinematic" },
  { id:"cinema-violet",  name:"Cinema · Paars/Rood",     ac:"#7c3aed", ac2:"#ef4444", bg:"#080612", pattern:"cinematic" },
  { id:"cinema-azure",   name:"Cinema · Blauw/Geel",     ac:"#2563eb", ac2:"#facc15", bg:"#050610", pattern:"cinematic" },
  { id:"cinema-tealmag", name:"Cinema · Teal/Magenta",   ac:"#0d9488", ac2:"#ec4899", bg:"#040a0c", pattern:"cinematic" },
  { id:"cinema-mono",    name:"Cinema · Mono",           ac:"#94a3b8", ac2:"#e2e8f0", bg:"#08090c", pattern:"cinematic" },
  // ── Photo achtergronden (ingebedde JPEGs van eigen design) ──
  { id:"sfeer-emerald", name:"Sfeer · Smaragd/Oranje",  ac:"#f59e0b", ac2:"#10b981", bg:"#06080a", pattern:"photo", bgImage:BG_EMERALD },
  { id:"sfeer-violet",  name:"Sfeer · Paars/Rood",      ac:"#ef4444", ac2:"#7c3aed", bg:"#080612", pattern:"photo", bgImage:BG_VIOLET  },
  { id:"sfeer-azure",   name:"Sfeer · Blauw/Geel",      ac:"#facc15", ac2:"#2563eb", bg:"#050610", pattern:"photo", bgImage:BG_AZURE   },
  { id:"sfeer-tealmag", name:"Sfeer · Teal/Magenta",    ac:"#ec4899", ac2:"#0d9488", bg:"#040a0c", pattern:"photo", bgImage:BG_TEALMAG },
  { id:"sfeer-mono",    name:"Sfeer · Mono",            ac:"#e2e8f0", ac2:"#94a3b8", bg:"#08090c", pattern:"photo", bgImage:BG_MONO    },

  // ══════ Vaste kleurenset (10 kleuren per type) ══════
  // ── Chevron ──
  { id:"chevron-rood", name:"Chevron · Rood", ac:"#e53935", bg:"#0f0707", pattern:"chevron" },
  { id:"chevron-blauw", name:"Chevron · Blauw", ac:"#1e88e5", bg:"#07080f", pattern:"chevron" },
  { id:"chevron-groen", name:"Chevron · Groen", ac:"#10b981", bg:"#050a07", pattern:"chevron" },
  { id:"chevron-geel", name:"Chevron · Geel", ac:"#facc15", bg:"#0a0a05", pattern:"chevron" },
  { id:"chevron-oranje", name:"Chevron · Oranje", ac:"#fb923c", bg:"#0a0703", pattern:"chevron" },
  { id:"chevron-rood-blauw", name:"Chevron · Rood/Blauw", ac:"#e53935", ac2:"#1e88e5", bg:"#080610", pattern:"chevron" },
  { id:"chevron-wit-groen", name:"Chevron · Wit/Groen", ac:"#f1f5f9", ac2:"#10b981", bg:"#060a07", pattern:"chevron" },
  { id:"chevron-oranje-zwart", name:"Chevron · Oranje/Zwart", ac:"#fb923c", ac2:"#6b7280", bg:"#0a0704", pattern:"chevron" },
  { id:"chevron-groen-geel", name:"Chevron · Groen/Geel", ac:"#10b981", ac2:"#facc15", bg:"#070a05", pattern:"chevron" },
  { id:"chevron-zwart-rood", name:"Chevron · Zwart/Rood", ac:"#8b939c", ac2:"#e53935", bg:"#0a0606", pattern:"chevron" },
  // ── Stadion ──
  { id:"stadium-blauw", name:"Stadion · Blauw", ac:"#1e88e5", bg:"#07080f", pattern:"stadium" },
  { id:"stadium-groen", name:"Stadion · Groen", ac:"#10b981", bg:"#050a07", pattern:"stadium" },
  { id:"stadium-geel", name:"Stadion · Geel", ac:"#facc15", bg:"#0a0a05", pattern:"stadium" },
  { id:"stadium-oranje", name:"Stadion · Oranje", ac:"#fb923c", bg:"#0a0703", pattern:"stadium" },
  { id:"stadium-rood-blauw", name:"Stadion · Rood/Blauw", ac:"#e53935", ac2:"#1e88e5", bg:"#080610", pattern:"stadium" },
  { id:"stadium-wit-groen", name:"Stadion · Wit/Groen", ac:"#f1f5f9", ac2:"#10b981", bg:"#060a07", pattern:"stadium" },
  { id:"stadium-oranje-zwart", name:"Stadion · Oranje/Zwart", ac:"#fb923c", ac2:"#6b7280", bg:"#0a0704", pattern:"stadium" },
  { id:"stadium-groen-geel", name:"Stadion · Groen/Geel", ac:"#10b981", ac2:"#facc15", bg:"#070a05", pattern:"stadium" },
  { id:"stadium-zwart-rood", name:"Stadion · Zwart/Rood", ac:"#8b939c", ac2:"#e53935", bg:"#0a0606", pattern:"stadium" },
  // ── Veld ──
  { id:"grass-rood", name:"Veld · Rood", ac:"#e53935", bg:"#0f0707", pattern:"grass" },
  { id:"grass-blauw", name:"Veld · Blauw", ac:"#1e88e5", bg:"#07080f", pattern:"grass" },
  { id:"grass-groen", name:"Veld · Groen", ac:"#10b981", bg:"#050a07", pattern:"grass" },
  { id:"grass-geel", name:"Veld · Geel", ac:"#facc15", bg:"#0a0a05", pattern:"grass" },
  { id:"grass-oranje", name:"Veld · Oranje", ac:"#fb923c", bg:"#0a0703", pattern:"grass" },
  { id:"grass-rood-blauw", name:"Veld · Rood/Blauw", ac:"#e53935", ac2:"#1e88e5", bg:"#080610", pattern:"grass" },
  { id:"grass-wit-groen", name:"Veld · Wit/Groen", ac:"#f1f5f9", ac2:"#10b981", bg:"#060a07", pattern:"grass" },
  { id:"grass-oranje-zwart", name:"Veld · Oranje/Zwart", ac:"#fb923c", ac2:"#6b7280", bg:"#0a0704", pattern:"grass" },
  { id:"grass-groen-geel", name:"Veld · Groen/Geel", ac:"#10b981", ac2:"#facc15", bg:"#070a05", pattern:"grass" },
  { id:"grass-zwart-rood", name:"Veld · Zwart/Rood", ac:"#8b939c", ac2:"#e53935", bg:"#0a0606", pattern:"grass" },
  // ── Stralen ──
  { id:"rays-rood", name:"Stralen · Rood", ac:"#e53935", bg:"#0f0707", pattern:"rays" },
  { id:"rays-blauw", name:"Stralen · Blauw", ac:"#1e88e5", bg:"#07080f", pattern:"rays" },
  { id:"rays-groen", name:"Stralen · Groen", ac:"#10b981", bg:"#050a07", pattern:"rays" },
  { id:"rays-geel", name:"Stralen · Geel", ac:"#facc15", bg:"#0a0a05", pattern:"rays" },
  { id:"rays-oranje", name:"Stralen · Oranje", ac:"#fb923c", bg:"#0a0703", pattern:"rays" },
  { id:"rays-rood-blauw", name:"Stralen · Rood/Blauw", ac:"#e53935", ac2:"#1e88e5", bg:"#080610", pattern:"rays" },
  { id:"rays-wit-groen", name:"Stralen · Wit/Groen", ac:"#f1f5f9", ac2:"#10b981", bg:"#060a07", pattern:"rays" },
  { id:"rays-oranje-zwart", name:"Stralen · Oranje/Zwart", ac:"#fb923c", ac2:"#6b7280", bg:"#0a0704", pattern:"rays" },
  { id:"rays-groen-geel", name:"Stralen · Groen/Geel", ac:"#10b981", ac2:"#facc15", bg:"#070a05", pattern:"rays" },
  { id:"rays-zwart-rood", name:"Stralen · Zwart/Rood", ac:"#8b939c", ac2:"#e53935", bg:"#0a0606", pattern:"rays" },
  // ── Halftone ──
  { id:"dots-rood", name:"Halftone · Rood", ac:"#e53935", bg:"#0f0707", pattern:"dots" },
  { id:"dots-blauw", name:"Halftone · Blauw", ac:"#1e88e5", bg:"#07080f", pattern:"dots" },
  { id:"dots-groen", name:"Halftone · Groen", ac:"#10b981", bg:"#050a07", pattern:"dots" },
  { id:"dots-oranje", name:"Halftone · Oranje", ac:"#fb923c", bg:"#0a0703", pattern:"dots" },
  { id:"dots-rood-blauw", name:"Halftone · Rood/Blauw", ac:"#e53935", ac2:"#1e88e5", bg:"#080610", pattern:"dots" },
  { id:"dots-wit-groen", name:"Halftone · Wit/Groen", ac:"#f1f5f9", ac2:"#10b981", bg:"#060a07", pattern:"dots" },
  { id:"dots-oranje-zwart", name:"Halftone · Oranje/Zwart", ac:"#fb923c", ac2:"#6b7280", bg:"#0a0704", pattern:"dots" },
  { id:"dots-groen-geel", name:"Halftone · Groen/Geel", ac:"#10b981", ac2:"#facc15", bg:"#070a05", pattern:"dots" },
  { id:"dots-zwart-rood", name:"Halftone · Zwart/Rood", ac:"#8b939c", ac2:"#e53935", bg:"#0a0606", pattern:"dots" },
  // ── Hexagon ──
  { id:"hex-rood", name:"Hexagon · Rood", ac:"#e53935", bg:"#0f0707", pattern:"hex" },
  { id:"hex-blauw", name:"Hexagon · Blauw", ac:"#1e88e5", bg:"#07080f", pattern:"hex" },
  { id:"hex-groen", name:"Hexagon · Groen", ac:"#10b981", bg:"#050a07", pattern:"hex" },
  { id:"hex-geel", name:"Hexagon · Geel", ac:"#facc15", bg:"#0a0a05", pattern:"hex" },
  { id:"hex-oranje", name:"Hexagon · Oranje", ac:"#fb923c", bg:"#0a0703", pattern:"hex" },
  { id:"hex-rood-blauw", name:"Hexagon · Rood/Blauw", ac:"#e53935", ac2:"#1e88e5", bg:"#080610", pattern:"hex" },
  { id:"hex-wit-groen", name:"Hexagon · Wit/Groen", ac:"#f1f5f9", ac2:"#10b981", bg:"#060a07", pattern:"hex" },
  { id:"hex-oranje-zwart", name:"Hexagon · Oranje/Zwart", ac:"#fb923c", ac2:"#6b7280", bg:"#0a0704", pattern:"hex" },
  { id:"hex-groen-geel", name:"Hexagon · Groen/Geel", ac:"#10b981", ac2:"#facc15", bg:"#070a05", pattern:"hex" },
  { id:"hex-zwart-rood", name:"Hexagon · Zwart/Rood", ac:"#8b939c", ac2:"#e53935", bg:"#0a0606", pattern:"hex" },
  // ── Cinema ──
  { id:"cinematic-rood", name:"Cinema · Rood", ac:"#e53935", bg:"#0f0707", pattern:"cinematic" },
  { id:"cinematic-blauw", name:"Cinema · Blauw", ac:"#1e88e5", bg:"#07080f", pattern:"cinematic" },
  { id:"cinematic-groen", name:"Cinema · Groen", ac:"#10b981", bg:"#050a07", pattern:"cinematic" },
  { id:"cinematic-geel", name:"Cinema · Geel", ac:"#facc15", bg:"#0a0a05", pattern:"cinematic" },
  { id:"cinematic-oranje", name:"Cinema · Oranje", ac:"#fb923c", bg:"#0a0703", pattern:"cinematic" },
  { id:"cinematic-rood-blauw", name:"Cinema · Rood/Blauw", ac:"#e53935", ac2:"#1e88e5", bg:"#080610", pattern:"cinematic" },
  { id:"cinematic-wit-groen", name:"Cinema · Wit/Groen", ac:"#f1f5f9", ac2:"#10b981", bg:"#060a07", pattern:"cinematic" },
  { id:"cinematic-oranje-zwart", name:"Cinema · Oranje/Zwart", ac:"#fb923c", ac2:"#6b7280", bg:"#0a0704", pattern:"cinematic" },
  { id:"cinematic-groen-geel", name:"Cinema · Groen/Geel", ac:"#10b981", ac2:"#facc15", bg:"#070a05", pattern:"cinematic" },
  { id:"cinematic-zwart-rood", name:"Cinema · Zwart/Rood", ac:"#8b939c", ac2:"#e53935", bg:"#0a0606", pattern:"cinematic" },

  // ══════ Arena-set (neon tunnel, serie 01) ══════
  { id:"arena-rood", name:"Arena · Rood", ac:"#ff2a2a", bg:"#0a0505", pattern:"photo", bgImage:"/images/arena-rood.jpg" },
  { id:"arena-blauw", name:"Arena · Blauw", ac:"#4aa6e8", bg:"#050a0f", pattern:"photo", bgImage:"/images/arena-blauw.jpg" },
  { id:"arena-blauw-rood", name:"Arena · Blauw/Rood", ac:"#2f6fff", ac2:"#d62828", bg:"#070409", pattern:"photo", bgImage:"/images/arena-blauw-rood.jpg" },
  { id:"arena-geel-rood", name:"Arena · Geel/Rood", ac:"#f4c81f", ac2:"#cf1f22", bg:"#080703", pattern:"photo", bgImage:"/images/arena-geel-rood.jpg" },
  { id:"arena-groen-geel", name:"Arena · Groen/Geel", ac:"#1faa52", ac2:"#e8dc3a", bg:"#050a07", pattern:"photo", bgImage:"/images/arena-groen-geel.jpg" },
  { id:"arena-zilver", name:"Arena · Zilver", ac:"#e2e8f0", bg:"#08090c", pattern:"photo", bgImage:"/images/arena-zilver.jpg" },
  { id:"arena-brons", name:"Arena · Brons", ac:"#d4a463", bg:"#09070a", pattern:"photo", bgImage:"/images/arena-brons.jpg" },
  { id:"arena-zwart-rood", name:"Arena · Zwart/Rood", ac:"#e2e8f0", ac2:"#e23b3b", bg:"#080809", pattern:"photo", bgImage:"/images/arena-zwart-rood.jpg" },

  // ══════ Neon-set (stadion met ringen, serie 02) ══════
  // Monochroom
  { id:"neon-rood",   name:"Neon · Rood",   ac:"#ff2d2d", ac2:"#ff2d2d", bg:"#0a0a0d", pattern:"photo", bgImage:"/images/stadium/stadium-rood.png" },
  { id:"neon-blauw",  name:"Neon · Blauw",  ac:"#2d5fff", ac2:"#2d5fff", bg:"#0a0a0d", pattern:"photo", bgImage:"/images/stadium/stadium-blauw.png" },
  { id:"neon-groen",  name:"Neon · Groen",  ac:"#28dc5a", ac2:"#28dc5a", bg:"#0a0a0d", pattern:"photo", bgImage:"/images/stadium/stadium-groen.png" },
  { id:"neon-geel",   name:"Neon · Geel",   ac:"#ffcd1e", ac2:"#ffcd1e", bg:"#0a0a0d", pattern:"photo", bgImage:"/images/stadium/stadium-geel.png" },
  { id:"neon-oranje", name:"Neon · Oranje", ac:"#ff8214", ac2:"#ff8214", bg:"#0a0a0d", pattern:"photo", bgImage:"/images/stadium/stadium-oranje.png" },
  { id:"neon-paars",  name:"Neon · Paars",  ac:"#aa46ff", ac2:"#aa46ff", bg:"#0a0a0d", pattern:"photo", bgImage:"/images/stadium/stadium-paars.png" },
  { id:"neon-cyaan",  name:"Neon · Cyaan",  ac:"#28d2eb", ac2:"#28d2eb", bg:"#0a0a0d", pattern:"photo", bgImage:"/images/stadium/stadium-cyaan.png" },
  { id:"neon-wit",    name:"Neon · Wit",    ac:"#ebf0ff", ac2:"#ebf0ff", bg:"#0a0a0d", pattern:"photo", bgImage:"/images/stadium/stadium-wit.png" },
  // Tweekleurig (thuis links · uit rechts)
  { id:"neon-blauw-rood",    name:"Neon · Blauw/Rood",    ac:"#2d5fff", ac2:"#ff2d2d", bg:"#0a0a0d", pattern:"photo", bgImage:"/images/stadium/stadium-blauw-rood.png" },
  { id:"neon-geel-groen",    name:"Neon · Geel/Groen",    ac:"#ffcd1e", ac2:"#28dc5a", bg:"#0a0a0d", pattern:"photo", bgImage:"/images/stadium/stadium-geel-groen.png" },
  { id:"neon-rood-geel",     name:"Neon · Rood/Geel",     ac:"#ff2d2d", ac2:"#ffcd1e", bg:"#0a0a0d", pattern:"photo", bgImage:"/images/stadium/stadium-rood-geel.png" },
  { id:"neon-oranje-blauw",  name:"Neon · Oranje/Blauw",  ac:"#ff8214", ac2:"#2d5fff", bg:"#0a0a0d", pattern:"photo", bgImage:"/images/stadium/stadium-oranje-blauw.png" },
  { id:"neon-groen-paars",   name:"Neon · Groen/Paars",   ac:"#28dc5a", ac2:"#aa46ff", bg:"#0a0a0d", pattern:"photo", bgImage:"/images/stadium/stadium-groen-paars.png" },
  { id:"neon-cyaan-magenta", name:"Neon · Cyaan/Magenta", ac:"#28d2eb", ac2:"#ff3ca0", bg:"#0a0a0d", pattern:"photo", bgImage:"/images/stadium/stadium-cyaan-magenta.png" },
];
